baseURL = "https://benjamin-philip.github.io/sicp/"
languageCode = "en-us"
title = "Ben's Solutions to Sicp"
theme = "hyde"

disableKinds = ["tags"]

[params]
  description = "My journey reading Sicp: From learning scheme to building an interpreter."
