#+TITLE: Sicp Ex 1.09

#+DATE: 2020-10-22

This is the First question in Section to of Chapter one in Sicp. Here we
are comparing recursion and iteration.

* The Question
  :PROPERTIES:
  :CUSTOM_ID: the-question
  :END:

*Exercise 1.9:*Each of the following two procedures defines a method for
adding two positive integers in terms of the procedures =inc=, which
increments its argument by 1, and =dec=, which decrements its argument
by 1.

#+BEGIN_SRC scheme
  (define (+ a b)
    (if (= a 0)
        b
        (inc (+ (dec a) b))))

  (define (+ a b)
    (if (= a 0)
        b
        (+ (dec a) (inc b))))
#+END_SRC

Using the substitution model, illustrate the process generated by each
procedure in evaluating =(+ 4 5)=. Are these processes iterative or
recursive?

* My Thoughts
  :PROPERTIES:
  :CUSTOM_ID: my-thoughts
  :END:

Before we start with this question, let us recap what is recursion and
what is iteration. (In simple language. I do not consider my words fit
to be a definition)

** What is Recursion?
   :PROPERTIES:
   :CUSTOM_ID: what-is-recursion
   :END:

A process is a Recursive Process only if the "shape" of the process
changes, and the data of the various steps involved is maintained by the
interpreter *internally*.

** What is Iteration?
   :PROPERTIES:
   :CUSTOM_ID: what-is-iteration
   :END:

A process is an iterative process only if the shape *does not* change
and the data of the various steps involved is maintained by a function
in the form of various parameters

* The Answer
  :PROPERTIES:
  :CUSTOM_ID: the-answer
  :END:

Let us manually evaluate =(+ 4 5)= where the process =+= is the first
definition. So:

#+BEGIN_SRC scheme
  (+ 4 5)
  (inc (+ 3 5)
  (inc (inc (+ 2 5)))
  (inc (inc (inc (+ 1 5))))
  (inc (inc (inc (inc (+ 0 5)))))
  (inc (inc (inc (inc 5))))
  (inc (inc (inc 6)))
  (inc (inc 7))
  (inc 8)
  9
#+END_SRC

We can see that the "shape" of the process changes. We also observe that
the number of levels =inc= was executed is only known by the
interpreter. Thus, we can say that is a *recursive process*

Now let us evaluate =(4 5)= where =+= is the second definition:

#+BEGIN_SRC scheme
  (+ 4 5)
  (+ 3 6)
  (+ 2 7)
  (+ 1 8)
  (+ 0 9)
#+END_SRC

We see that the "shape" of the process remains the same. We should also
note that the information where the Interpreter is maintained by the
function. We can hence, conclude that that this is an *iterative
process*.
