#+TITLE: Sicp Ex 1.35

#+DATE: 2021-02-02

This is the $35^{th}$ exercise from Sicp. Here, we calculate the golden
ratio ($\varphi$) by finding the fixed point of a function. {{.Site.Params.Title}}

* The Question
  :PROPERTIES:
  :CUSTOM_ID: the-question
  :END:

*Exercsie 1.35:* Show that the golden ratio $\varphi$ (Section 1.2.2) is
a fixed point of the transformation $x \mapsto 1 + 1/x$ , and use this
fact to compute $\varphi$ by means of the fixed-point procedure.

* The Answer
  :PROPERTIES:
  :CUSTOM_ID: the-answer
  :END:

This is simple. We already know that $\varphi$ is equal to
$\frac{1 + \sqrt{5}}{2}$. (Refer Exercise 1.13) A quick division gives
us 1.6180 as the representation in float.

All we now need to do is use the =fixed-point= function and pass it a
=lambda= of the function $1 + 1/x$

#+BEGIN_SRC scheme
  ;; fixed-point function
  (define tolerance 0.00001)
  (define (fixed-point f first-guess)
    (define (close-enough? v1 v2)
      (< (abs (- v1 v2))
         tolerance))
    (define (try guess)
      (let ((next (f guess)))
        (if (close-enough? guess next)
            next 
            (try next))))
    (try first-guess))
#+END_SRC

We shall use 1 as the initial guess. The following is the lambda

#+BEGIN_SRC scheme
  (lambda (x)(+ 1 (/ 1 x)))
#+END_SRC

And testing:

#+BEGIN_SRC scheme
  (fixed-point (lambda (x)(+ 1 (/ 1 x))) 1.0)

  ;Value: 1.6180327868852458
#+END_SRC

There you go! That wasn't too complicated was it ?
